version: '3.8'

services:
  # Keycloak Identity and Access Management
  keycloak:
    image: keycloak/keycloak:26.5.2
    container_name: nodeorb-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
    ports:
      - "8086:8080"
    networks:
      - keycloak-network
    command: start-dev
    restart: unless-stopped

networks:
  keycloak-network:
    driver: bridge