apiVersion: 1
providers:
  - name: "Nodeorb Dashboards"
    type: file
    options:
      path: /etc/grafana/provisioning/dashboards
      foldersFromFilesStructure: true

datasources:
  - name: "Prometheus"
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: "Elasticsearch"
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      timeField: "@timestamp"
      interval: Daily

  - name: "Zipkin"
    type: zipkin
    access: proxy
    url: http://zipkin:9411
